import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { routes } from './app.routes';
import { AuthInterceptor } from './core/interceptors/auth.interceptor';
import { provideCharts, withDefaultRegisterables } from 'ng2-charts';
import { provideIcons } from '@ng-icons/core';
import {
   lucideWallet,
   lucideTrendingUp,
   lucideTrendingDown,
   lucideFilter,
   lucideX,
   lucideMoveUp,
   lucideMoveDown,
   lucideArrowLeft,
   lucideArrowRight,
   lucideTrash,
   lucidePencil,
   lucideSquarePen,
   lucidePlus,
   lucideLink,
   lucideLock,
   lucideEye,
   lucideEyeOff,
   lucideCircleCheckBig,
   lucideLayoutDashboard,
   lucideLayers,
   lucideCreditCard,
   lucideChartColumnBig,
   lucideRadio,
   lucideUser,
   lucideDatabase,
   lucideTag,
   lucideMoon,
   lucideSun,
   lucideLogOut,
   lucideMail,
   lucideDollarSign,
   lucideMenu,
   lucideFunnel,
   lucideBell,
   lucideChevronDown,
   lucideLoader,
   lucideChevronLeft,
   lucideChevronRight,
   lucideCircleX,
} from '@ng-icons/lucide';

export const appConfig: ApplicationConfig = {
   providers: [
      provideZoneChangeDetection({ eventCoalescing: true }),
      provideRouter(routes),
      provideHttpClient(withInterceptors([AuthInterceptor])),
      provideCharts(withDefaultRegisterables()),
      provideIcons({
         lucideWallet,
         lucideTrendingUp,
         lucideTrendingDown,
         lucideFilter,
         lucideX,
         lucideMoveUp,
         lucideMoveDown,
         lucideArrowLeft,
         lucideArrowRight,
         lucideTrash,
         lucidePencil,
         lucideSquarePen,
         lucidePlus,
         lucideLink,
         lucideLock,
         lucideEye,
         lucideEyeOff,
         lucideCircleCheckBig,
         lucideLayoutDashboard,
         lucideLayers,
         lucideCreditCard,
         lucideChartColumnBig,
         lucideRadio,
         lucideUser,
         lucideDatabase,
         lucideTag,
         lucideMoon,
         lucideSun,
         lucideLogOut,
         lucideMail,
         lucideDollarSign,
         lucideMenu,
         lucideFunnel,
         lucideBell,
         lucideChevronDown,
         lucideLoader,
         lucideChevronLeft,
         lucideChevronRight,
         lucideCircleX,
      }),
   ],
};
